### ISSUE TITLE
Discrepancy between treewidth and largest intermediate tensor of a contraction plan

### ISSUE THREAD

**Issue by brenjohn** [JuliaQX/QXTools.jl#10]
When contracting a network according to some contraction plan, the size of the largest intermediate tensor may be greater than the treewidth of the elimination order used to create the contraction plan.

**Comment by nmoran** [comment]
Have discovered this is due to edges which do not appear to be hyper edges when looking at the local context, but are actually hyper edges when looking at the larger context. Solution to dealing with these is to perform an optimisation step to identify these on the largest contraction flow this down to smaller operations. This is in progress on QXContexts side.
